Repository openrewrite/rewrite-jenkins, pull requests merged in 2023-08, with the labels that each got.

#35 Add .editorconfig as seen elsewhere & reformat tests
  src/test/java/org/openrewrite/jenkins/.editorconfig
  src/test/java/org/openrewrite/jenkins/AddPluginsBomTest.java
  src/test/java/org/openrewrite/jenkins/BomLookupTest.java
  src/test/java/org/openrewrite/jenkins/CreateIndexJellyTest.java
  src/test/java/org/openrewrite/jenkins/DisableLocalResolutionForParentPomTest.java
  src/test/java/org/openrewrite/jenkins/IsJenkinsPluginTest.java
  src/test/java/org/openrewrite/jenkins/JavaxAnnotationsToSpotBugsTest.java
  src/test/java/org/openrewrite/jenkins/ModernizeJenkinsfileTest.java
  src/test/java/org/openrewrite/jenkins/ModernizePluginForJava8Test.java
  src/test/java/org/openrewrite/jenkins/ReplaceLibrariesWithApiPluginTest.java
  src/test/java/org/openrewrite/jenkins/UpgradeHtmlUnit_3_3_0Test.java
  src/test/java/org/openrewrite/jenkins/UpgradeVersionPropertyTest.java
  src/test/java/org/openrewrite/jenkins/migrate/hudson/UtilGetPastTimeStringToTimeSpanStringTest.java
Labels: enhancement

#34 Introduce AddTeamToCodeowners Recipe
  src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
  src/main/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGenerator.java
  src/main/java/org/openrewrite/jenkins/github/TeamNameGenerator.java
  src/main/java/org/openrewrite/jenkins/github/TeamNameInput.java
  src/main/java/org/openrewrite/jenkins/github/package-info.java
  src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java
  src/test/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGeneratorTest.java
Labels: recipe

#37 CODEOWNERS Enhancements
  src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
  src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java
Labels: bug, enhancement

#48 Override and Exclude Known Team Names
  src/main/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGenerator.java
  src/main/java/org/openrewrite/jenkins/github/InMemoryTeamNameValidator.java
  src/main/resources/org/openrewrite/jenkins/github/teams.properties
  src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java
  src/test/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGeneratorTest.java
  src/test/java/org/openrewrite/jenkins/github/InMemoryTeamNameValidatorTest.java
  src/test/resources/plugin-developers-teams.txt
  src/test/resources/updatecenter-artifactIds.txt
Labels: bug, enhancement
